### PR TITLE
Remove dependencies

### PR DESCRIPTION
**Pull request by bdovaz**
Remove unnecessary System.Runtime.InteropServices dependency.

### CODE REVIEW

**Comment by bdovaz** [comment]
@AArnott can you release a new NuGet package version without this dependency? Thanks.

**Comment by AArnott** [comment]
How is this blocking you?

**Comment by bdovaz** [comment]
Yes because we use it with Unity and it only supports .NET Standard 2.0 / 2.1 packages.

We use it with:

https://github.com/xoofx/UnityNuGet

**Comment by AArnott** [comment]
Ok. 2.6.13 is on its way to nuget.org now.

**Comment by bdovaz** [comment]
Thanks, but that UnityNuGet library only works with stable versions...

**Comment by AArnott** [comment]
Then you'll need to send a PR to our latest stable branch instead of our main development branch.

**Comment by bdovaz** [comment]
@AArnott what's branch is it?

https://github.com/AArnott/Validation/branches/all

Thanks!

**Comment by AArnott** [comment]
Oh, gosh. I guess in this repo I don't have a stable branch for v2.5. Let me get back to you on that.

**Comment by AArnott** [comment]
Ok. I've pushed a v2.5 branch and cherry-picked your change to it. We'll get a stable 2.5 release out to nuget.org today.

**Pull request merged**
